---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: / ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "DataRescue[EventName]"
keywords:    ""
description: "A single-page template for Jekyll based blogs (like what you'd use on github pages!)"
source_link: "https://github.com/t413/SinglePaged"
favicon:     #put a path like: "img/favicon.ico"
touch_icon:  #put a path like: "img/apple-touch-icon.png"


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'

kramdown:
  auto_ids:  false
